In [1]:
import numpy as np
#lets assume we got different kind of diets observation
diet_a = np.random.normal(2, 0.5, 100)
diet_b = np.random.normal(2.1, 0.5, 100)
diet_a,diet_b

(array([2.12322323, 1.73701015, 2.41512375, 2.06076024, 1.41925582,
        2.27839119, 1.22172294, 1.74909951, 2.73889427, 2.26805462,
        1.71730403, 0.89763557, 1.52380096, 2.74329661, 1.94494541,
        2.24931587, 2.42120543, 1.95778479, 2.05863351, 1.76993299,
        2.2798228 , 0.99407642, 2.84174009, 2.16437039, 2.057112  ,
        2.61117887, 1.33694559, 2.59504122, 2.1482675 , 1.76709013,
        2.58194766, 1.97182125, 2.8708389 , 1.73643522, 1.74921019,
        2.13226019, 1.97345674, 1.98018208, 2.04781982, 1.84583873,
        0.58392021, 2.13844942, 1.0788693 , 2.25889609, 1.34720256,
        2.95559118, 2.03032357, 1.38459375, 1.45714124, 1.97805894,
        2.71139683, 2.09460111, 1.63470129, 1.56518059, 1.95872712,
        2.005534  , 2.13067536, 2.64764732, 2.5932257 , 1.13465838,
        2.05030654, 2.04378229, 2.60666515, 1.39528719, 1.56056465,
        2.57894993, 2.58011605, 2.19823603, 2.04804369, 0.70674863,
        1.95760333, 2.37817183, 2.37541875, 1.57

In [6]:
from sklearn.datasets import make_regression

X, y = make_regression(n_samples=100, n_features=1, noise=10)

# Scale the target variable y to a Likert scale by mapping the continuous values to integers
y_scaled = (y / abs(y.max())) * 5 + 1
y_scaled = y_scaled.round().astype(int)
y.shape,y,y_scaled


((100,),
 array([ -0.73065946,  10.10377398,   0.15264956,  32.90687648,
         12.80728639,  12.00201929,   4.43621236,  -1.38260524,
          7.47531733,  14.53807228,  -8.21918886,  10.87933538,
        -16.96762237,  -5.39818782,   0.68718617,   1.84431894,
         17.43506555,  17.20558147,  10.81661476, -16.67748944,
          2.70424712,   4.85811388,   7.43513312,  20.65308766,
         -4.40242654,   6.28572689,  11.81389846,  -7.84782509,
          8.23805739,  -4.07124247,  16.31426518, -18.43795104,
        -14.51891242,   7.71345394,  13.30019013,  21.79558496,
         -1.06079574,  13.33965665,   0.5469536 ,  12.40840894,
        -12.97146032,   6.01105711,  -1.76778171, -14.15989431,
        -17.79326659, -11.90395085, -10.0140173 ,  11.7802404 ,
          4.43553652, -19.20113597,   0.09909907,  30.2699965 ,
         12.02226948,   1.43132994,  -1.14371812,  25.74660046,
         13.50601488, -21.50074917, -16.85866003, -25.71561029,
         -2.47378355, -12.13383

In [12]:
# from sklearn.datasets import make_regression
import numpy as np

# Generate data for the first latent variable
X1, y1 = make_regression(n_samples=100, n_features=5, noise=10)
y1 = (y1 / abs(y1.max())) * 5 + 1
y1 = y1.round().astype(int)

# Generate data for the second latent variable
X2, y2 = make_regression(n_samples=100, n_features=5, noise=10)
y2 = (y2 / abs(y2.max())) * 5 + 1
y2 = y2.round().astype(int)

# Generate data for the third latent variable
X3, y3 = make_regression(n_samples=100, n_features=5, noise=10)
y3 = (y3 / abs(y3.max())) * 5 + 1
y3 = y3.round().astype(int)

# Generate data for the fourth latent variable
X4, y4 = make_regression(n_samples=100, n_features=5, noise=10)
y4 = (y4 / abs(y4.max())) * 5 + 1
y4 = y4.round().astype(int)

# Generate data for the fifth latent variable
X5, y5 = make_regression(n_samples=100, n_features=5, noise=10)
y5 = (y5 / abs(y5.max())) * 5 + 1
y5 = y5.round().astype(int)

# Combine the data for all latent variables
X = np.hstack((X1, X2, X3, X4, X5))
y = np.hstack((y1, y2, y3, y4, y5))

X,y


(array([[ 2.01052432, -1.00709905, -0.87291125, ...,  0.16870143,
          1.26850494, -0.26627763],
        [ 0.2241323 ,  1.1497187 , -0.34577335, ..., -0.92422613,
          0.93311915, -0.18324174],
        [ 1.22825704,  0.13890215, -2.63093179, ...,  1.28156692,
          0.37074679, -0.28180278],
        ...,
        [-1.39605402,  0.14356754,  1.9638396 , ..., -2.48501609,
         -0.57401332,  0.48754026],
        [-1.61631368,  1.6570262 , -1.19250757, ..., -0.08691856,
          1.31992966,  0.31371456],
        [-1.31202806,  1.41913261, -0.51738889, ..., -0.27527606,
         -0.01514184, -0.74882143]]),
 array([ 5,  3,  4,  2, -1,  2,  5,  2, -2,  6,  2,  1,  3,  1,  3, -1, -1,
         1,  1,  1,  4, -1, -2, -3,  3, -2, -5,  1, -1, -1,  0,  1,  3,  2,
         2, -1,  2, -1,  3,  2, -1,  2,  3,  3,  1,  1,  3,  3,  3,  2, -1,
         4,  5,  1,  5, -1, -2, -1,  2,  2, -1, -3,  1,  1,  2,  1,  3,  2,
         1, -1,  2,  1,  2, -1,  3,  1,  5, -2,  1,  1,  3, -2, -1,  

In [13]:
#explain the variance using scikit
from sklearn.linear_model import LinearRegression
from sklearn.metrics import explained_variance_score

# Example data
X = [[0, 0], [0, 1], [1, 0], [1, 1]]
y = [0, 1, 1, 2]

# Create and fit the linear regression model
model = LinearRegression()
model.fit(X, y)

# Predict the target variable
y_pred = model.predict(X)

# Calculate the explained variance
evs = explained_variance_score(y, y_pred)
print("Explained variance: ", evs)


Explained variance:  1.0


In [16]:
#latent and response variable

# Generate data for the predictors (X) and response variables (Y)
X, Y = make_regression(n_samples=50, n_features=5, noise=10)

# Generate data for the latent variables (T)
T = np.random.normal(0, 1, size=(50, 3))

# Calculate the loading vectors (w)
w = np.linalg.lstsq(X, T, rcond=None)

# Calculate the regression coefficients (b)
b = np.linalg.lstsq(T, Y, rcond=None)[0]
T,w,b

(array([[-1.36192878e-01, -1.71547104e+00,  1.11622906e+00],
        [ 1.72184937e-01, -8.59811190e-01,  4.48067806e-01],
        [-2.62499027e+00, -2.09340701e+00,  1.48884272e+00],
        [-7.56518149e-01, -1.42780543e-01, -9.85598292e-01],
        [ 7.94757322e-01, -1.22708124e+00, -2.10156959e-01],
        [-1.91590312e-01,  1.04531486e+00, -3.11096598e-01],
        [-6.11457119e-01,  7.10134023e-01, -1.28971693e+00],
        [ 1.62571244e+00, -5.53722025e-01,  4.16333362e-01],
        [-1.32336025e-03,  1.23395281e+00,  2.14475627e-01],
        [-7.55791235e-01,  5.02977789e-01,  1.20522784e+00],
        [-7.43684408e-01,  6.95066727e-01, -5.46105641e-01],
        [-5.23516974e-01,  1.18840138e+00, -1.19492407e+00],
        [-7.17765362e-01,  4.68490765e-01, -7.68111463e-01],
        [ 2.59837344e-01,  2.05822934e+00,  6.43622311e-02],
        [ 3.34716723e-02, -1.07070960e+00, -1.09661597e+00],
        [-9.52563899e-01,  2.29986936e-01, -1.08905531e-01],
        [-6.28312069e-01