In [1]:
import numpy as np
import sympy as sym
from sympy.abc import *

# x = sym.Symbol('x')
# f = 2*x**4+1
# f.integrate(x),f.diff(x)
# print(df)
# np.differ
# help(sym.Sum)
# sym.Sum(2*x,(n,0,j))
expr = 2/y
expr = expr.subs(y,1/x)
expr




2*x

markdown yoo
$$
e=2+\frac{1}{1+\frac{1}{2+\frac{1}{1+\frac{1}{1+\frac{1}{4+\frac{1}{1+\frac{1}{1+\frac{1}{6+\cdots}}}}}}}}
$$

In [2]:
import scipy.stats
import numpy as np

k = 0.1  # Laplace smoothing parameter

# Compute the counts of each word
counts = {"cat": 10, "dog": 5}

# Add the Laplace smoothing parameter to the count of each word
smoothed_counts = {word: count + k for word, count in counts.items()}

# Fit a Laplace distribution to the data
laplace_dist = scipy.stats.laplace(scale=k)

# Compute the probability of each word
probs = {word: laplace_dist.pdf(count) for word, count in smoothed_counts.items()}

probs


{'cat': 6.842697355869361e-44, 'dog': 3.547737081142377e-22}

In [3]:
#transposing
# import numpy as np
row_vector = np.array([[10,20,30]])
col_vector = row_vector.T
col_vector*5

array([[ 50],
       [100],
       [150]])

In [6]:
from sympy import cos,sin,lambdify
one = cos(1)**2+sin(1)**2
one.evalf()-1

0

In [5]:
eqq = sin(x)
eqq.evalf(subs={x:3})

0.141120008059867

In [21]:
#evaluating using numpy at a thousand points
aM = np.random.randint(3,size=(5))
lambdify(x,eqq,'numpy')(aM),aM


(array([0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.90929743]),
 array([1, 1, 1, 1, 2]))